config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :labels
  # authenticated :user do
    root to: "dashboard#index"
  # end
  get 'notices/update_notice', to: 'notices#update_notice'
  get 'mypage', to: 'users#mypage', as: 'mypage'
  get 'users/update_user_after_login', to: 'users#update_user_after_login', as: 'update_user_after_login'
  get 'stamps/remove_stamp', to: 'stamps#remove_stamp', as: 'remove_stamp'
  get 'stamps/press_stamp', to: 'stamps#press_stamp', as: 'press_stamp'
  get 'dashboard/index', to: 'dashboard#set_current_company', as: 'set_current_company'
  get 'companies/associate_intern', to: 'companies#associate_intern', as: 'associate_intern'
  get 'attendances/start_work', to: 'attendances#start_work', as: 'start_work'
  get 'attendances/stop_work', to: 'attendances#stop_work', as: 'stop_work'
  get 'attendances/start_break', to: 'attendances#start_break', as: 'start_break'
  get 'attendances/stop_break', to: 'attendances#stop_break', as: 'stop_break'
  resources :stamps
  resources :companies
  resources :todos
  resources :notices
  resources :attendances
  resources :goals
  resources :reports
  resources :schedules
  resources :tasks
  devise_scope :user do
    patch "users/confirmation", to: "users/confirmations#confirm"
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: "users/confirmations"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :users, only: [] do
    get "/schedules", to: "schedules#selected_user_schedules", as:"selected_user_schedules"
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    redirect_to update_user_after_login_path if session[:after_sign_up] == true
    session[:mypage] = false

    if current_company != nil
      @schedules = current_company.schedules.all
      @tasks_not_desided_day = []
      tasks = current_company.tasks
      tasks.each do |task|
        if task.schedules == []
          @tasks_not_desided_day.append(task)
        end
      end


      @reports = current_company.reports.limit(5).reverse_order
      users = current_company.users.where(employment_status:1)
      @users = users.page(params[:page]).per(10)

      if current_user.employment_status == false
        #社員用トップ
        @user = current_company.users.find(current_user.id)
        @active_attendances = Attendance.where(company_id: current_company, work_stopped_at: nil)
        range = Time.now.next_day.beginning_of_day...Float::INFINITY
        @schedules_for_staff = current_company.schedules.where(work_started_at: range).order(:work_started_at).limit(5)
        @searched_users = User.all.page(params[:page]).per(10).search(params[:search])
        @todo_users = @user.todo_users.reverse_order
      else
        @user = current_company.users.find(current_user.id)
        #4 buttons
        if @user.attendances != []
          now_time = Time.now.to_time.to_i
          work_started_time = @user.attendances.last.work_started_at.to_i
          work_stopped_time = @user.attendances.last.work_stopped_at.to_i
          break_started_time = @user.attendances.last.break_started_at.to_i
          break_stopped_time = @user.attendances.last.break_stopped_at.to_i
          @break_time = 0.to_i if attendance_status(user:@user) == "am_work"
          @break_time = now_time - break_started_time if attendance_status(user:@user) == "break"
          @break_time = break_stopped_time - break_started_time if attendance_status(user:@user) == "pm_work" || attendance_status(user:@user) == "not_work"
          @attendance_time = now_time - work_started_time - @break_time
          @last_attendance_time = work_stopped_time - work_started_time - @break_time.to_i if attendance_status(user:@user) == "not_work"
        end

        from_now_on = Time.now.beginning_of_day...Float::INFINITY
        @future_schedules = current_user.schedules.where(work_started_at:from_now_on, company_id:current_company.id)
        @user_tasks_not_desided_day = []
        user_tasks = current_user.tasks
        user_tasks.each do |user_task|
          if user_task.schedules == []
            @user_tasks_not_desided_day.append(user_task)
          end
        end
        range = Time.now.next_day.beginning_of_day...Float::INFINITY
        @schedules_for_intern = current_company.schedules.where(work_started_at: range, user_id:current_user.id).order(:work_started_at).limit(5)

        @schedule = Schedule.new
      end
    end
  end

  def set_current_company
    session[:company_id] = params[:company_id]
    redirect_back(fallback_location: root_path)
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_4buttons.html.erb
<div class="four ui buttons">
  <%= link_to '出勤', start_work_path,class:"ui button" if attendance_status(user:@user) == "not_work"  || attendance_status(user:@user) == "never_work"%>
  <%= link_to '休憩開始', start_break_path,class:"ui button" if attendance_status(user:@user) == "am_work"%>
  <%= link_to '休憩終了', stop_break_path,class:"ui button" if attendance_status(user:@user) == "break"%>
  <%= link_to '退勤', stop_work_path,class:"ui button" if attendance_status(user:@user) == "am_work" || attendance_status(user:@user) == "pm_work"%>
</div>

app/views/dashboard/_attendance_status_for_intern.html.erb
<script src="https://webkaru.net/jquery-plugin/sources/timeto/jquery.timeTo.js"></script>
<link href="https://webkaru.net/jquery-plugin/sources/timeto/timeTo.css" type="text/css" rel="stylesheet"/>

<!--
<div id="countdown" class="timeTo timeTo-white" style="font-size: 28px;"></div>
<script>
  $('#countdown').timeTo();
  </script>-->

  <h3>勤務状況</h3>
  <% if @user.attendances != [] %>
  <% if @user.attendances.last.work_stopped_at.nil? %>
  <% if @user.attendances.last.break_started_at.nil? == @user.attendances.last.break_stopped_at.nil? %>
    <div class="ui grid padded stackable middle aligned">
      <div class="sixteen wide column center aligned">
        <div class="ui piled red segment">
          <h1>出勤中</h1>
        </div>
        本日の勤務時間：<%= (Time.parse("1/1") + @attendance_time).strftime("%-H時間%-M分%-S秒") %><br>
        休憩時間：<%= (Time.parse("1/1") + @break_time).strftime("%-H時間%-M分%-S秒") %>
      </div>
    </div>
  <% else %>
    <div class="ui grid padded stackable middle aligned">
      <div class="sixteen wide column center aligned">
        <div class="ui piled red segment">
          <h1>休憩中</h1>
        </div>
        勤務時間：<%= (Time.parse("1/1") + @attendance_time).strftime("%-H時間%-M分%-S秒") %><br>
        休憩時間：<%= (Time.parse("1/1") + @break_time).strftime("%-H時間%-M分%-S秒") %><br>
      </div>
    </div>
  <% end %>
  <% else %>
  <% #退勤中の場合 %>
    <div class="ui grid padded stackable middle aligned">
      <div class="sixteen wide column center aligned">
        <div class="ui piled yellow segment">
          <h1>退勤中</h1>
        </div>
        前回勤務時間：<%= (Time.parse("1/1") + @last_attendance_time).strftime("%-H時間%-M分%-S秒") %>
      </div>
    </div>
    <% end %>
    <% else %>
    <% #初回出社前の場合 %>
    <div class="ui grid padded stackable middle aligned">
      <div class="sixteen wide column center aligned">
        <div class="ui piled yellow segment">
          <h1>退勤中</h1>
        </div>
      </div>
    </div>
    <% end %>
    <div class="four ui buttons">
      <%= link_to '出勤', start_work_path,class:"ui button" if attendance_status(user:@user) == "not_work"  || attendance_status(user:@user) == "never_work"%>
      <%= link_to '休憩開始', start_break_path,class:"ui button" if attendance_status(user:@user) == "am_work"%>
      <%= link_to '休憩終了', stop_break_path,class:"ui button" if attendance_status(user:@user) == "break"%>
      <%= link_to '退勤', stop_work_path,class:"ui button" if attendance_status(user:@user) == "am_work" || attendance_status(user:@user) == "pm_work"%>
    </div>

app/views/dashboard/_invite_intern.html.erb
<div class="ui raised segment">
  <h3>新しいインターン生を招待</h3>
  ユーザ検索
  <%= form_tag root_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "検索", :name => nil %>
  <% end %>
  <% if params[:search] != nil %>
    <% @searched_users.each do |searched_user| %>
      <%= link_to searched_user do%>
        <div class="wrap-for-dev">
          <div>
            <%= image_tag searched_user.profile_photo_url%>
          </div>
          <div>
            <div>
              <h3><%= searched_user.name %></h3>
            </div>
            <div>
              <%= searched_user.university %> <%= searched_user.department %> <%= searched_user.grade %>年
            </div>
          </div>
          <div>
            <%= link_to '詳細', searched_user ,class: "btn btn-default"%>
            <%= link_to 'チームに招待', associate_intern_url(:user_id => searched_user.id, :user_name => searched_user.name, :company_id => current_user.company_users.first.company.id)%>
          </div>
        </div>
      <% end %>
    <% end %>
    <%= paginate @searched_users %>
  <% end %>
</div>

app/views/dashboard/_no_company.html.erb
<div style="width: 100%; text-align:center;">
  <h1>インテルネへようこそ！</h1>

  <h3>現在、会社に所属しておりません。</h3>
  <h3>社員の方に招待してもらいましょう！</h3>
</div>

app/views/dashboard/_notice_list.html.erb
<div class="ui raised segment">
  <h3>お知らせ</h3>
  <div class="ui relaxed divided list">
    <% recent_notice_users.each do |notice_user| %>
      <%= link_to notice_path(notice_user.notice), class:"item future" do %>
  	    <i class="large info circle middle aligned icon"></i>
  	    <div class="content">
  	      <div class="header"><%= notice_user.notice.body %></div>
  	      <div class="description">
  		      <% notice_time = Time.now.to_time.to_i - notice_user.notice.created_at.to_time.to_i %>
  		      <%= (Time.parse("1/1") + notice_time).strftime("%-H時間%-M分%-S秒前") %>
  	      </div>
  	    </div>
      <% end %>
    <% end %>
  </div>
  <%= link_to '全てのお知らせを見る', notices_path %>
</div>

app/views/dashboard/_reports.html.erb
<script type="text/javascript">
		$(document).ready(function(){
			$('.ui.dropdown').dropdown();
		});
</script>
<h3>日報
	<% if current_user.employment_status == true %>
		<%= link_to new_report_path, class: "ui right floated button interne-icon-btn" do%>
			<i class="plus icon"></i>
		<% end %>
	<% end %>
</h3>
<div class="ui two cards stackable" style="margin-left:-1em; margin-right:-1em; margin-top:0px; margin-bottom:0px;">
  <% @reports.each do |report| %>
  <div class="card">
    <div class="content" style="background-image: url('../assets/mima-opa.png');background-position: right bottom; background-repeat: no-repeat;">
      <% if report.user_id == current_user.id %>
      <div class="ui dropdown right floated">
      	<i class="options icon"></i>
      	<div class="menu">
      		    <%= link_to report ,class: "item" do%>詳細<% end%>
      		    <%= link_to edit_report_path(report) ,class: "item" do%>編集<% end%>
      		    <%= link_to report, method: :delete, data: { confirm: '本当に削除しますか？' } ,class: "item" do%>削除<%end%>
      	</div>
      </div>
      <% end %>
      <div class="meta">
        <%= report.schedule.work_started_at.strftime('%m/%d') %>
      </div>
      <div class="header">
				<%= report.title %>
      </div>
      <div class="description">
        <div style="font-size:10px;"><%= report.body %></div>
      </div>
    </div>
    <div class="extra content" style="padding: 1.5em 1em;">
			<% color = user_color_list(user_id:report.user.id,company_id:current_company.id) %>
			<div class="circle-image-border" style="width: 40px; height: 40px; left: 1rem; margin-top: -20px;  background: linear-gradient(-45deg,<%= color.grad_1 %>,<%= color.grad_2 %>);">
				<span><%= image_tag report.user.profile_photo_url, class:"company-icon-img"%></span>
			</div>
			<div style="padding-left:3.5rem;"><%= report.user.name %></div>
		</div>
    <div class="extra content">
	    <div class="item">
	      <% report.report_stamps.each_with_index do |report_stamp,i| %>
	      	<%if i==0 && report.report_stamps.length==1 %>
	      	  <%= image_tag report_stamp.stamp.url ,class:"ui mini image left floated",style:"width:17px;height:17px;margin-bottom:0px;margin-right:0.5em;"%>
	      	  <div class="left floated" style="font-size:9px;"><%= report_stamp.user.name %></div>
	      	<%elsif i==0%>
	      	  <%= image_tag report_stamp.stamp.url ,class:"ui mini image left floated",style:"width:17px;height:17px;margin-bottom:0px;margin-right:0.5em;"%>
	      	  <div class="left floated" style="font-size:9px;"><%= report_stamp.user.name %>など<%= report.report_stamps.length %>人</div>
	      	<%end%>
		　   <% end %>
	    <div class="ui dropdown right floated" style="display:block;display: flow-root;">
        <div style="font-size:9px">スタンプ送信</div>
          <div class="menu">
            <% stamps.each do |stamp| %>
              <div class="item">
              <%= link_to press_stamp_path(stamp_id:stamp.id,associate_type:"report",associate_id:report.id) do%>
                  <%= image_tag stamp.url %>
              <% end %>
              </div>
            <% end %>
          </div>
        </div>
	    </div>
    </div>
  </div>
  <% end %>
</div>

app/views/dashboard/_schedules.html.erb
<script>
// Place all the behaviors and hooks related to the matching controller here.
// All this logic will automatically be available in application.js.
// You can use CoffeeScript in this file: http://coffeescript.org/


//ユニークなkey取得
const tallyTarget = target => {
	// ObjectからKeyを重複なく取得
	const keys = _.uniq(_.flatten(target.map(t => Object.keys(t))))
	// keyで抽出する(pluck)
	const result = {}
	keys.forEach(k => result[k] = _.compact(_.map(target, k)))
	return result
};
//時間の数字の０詰め
var toDoubleDigits = function(num) {
  num += "";
  if (num.length === 1) {
    num = "0" + num;
  }
 return num;
};

shoya =[
<% @schedules.each do |schedule| %>
	<% color = user_color_list(user_id:schedule.user.id,company_id:current_company.id) %>
	  {
			title:'',
			open_div:'<div class="schedule-events" style="background:<%=color.bg%>">',
			border:'<div class="left-gradient-border" style="background: linear-gradient(-45deg,<%= color.grad_1 %>,<%= color.grad_2 %>);"></div>',
    	username:'<div class="username" style="color:<%= color.main %>"><%= schedule.user.name %></div>',
			schedule:'<div class="schedule"><%= schedule.work_started_at.strftime("%-H:%M") %> ~ <%= schedule.work_ended_at.strftime("%-H:%M") %></div>',
    	tasks:'<% schedule.tasks.each do |task| %><div class="task"><% task.labels.each do |label| %><div class="label" style="background-color:<%= label.color %>;"><%= label.name %></div><% end %><%= task.title %></div><% end %>',
			close_div:'</div>',
			start:'<%= schedule.work_started_at.time.strftime('%Y/%m/%d %H:%M:%S') %>',
    	end:'<%= schedule.work_ended_at.time.strftime('%Y/%m/%d %H:%M:%S') %>'
    },
  <% end %>
];

$(document).ready(function() {
	var nowdate = new Date();

	event_perse = tallyTarget(shoya);
	uniq_title = _.uniq(event_perse.title);

	for(var i=0;i<uniq_title.length;i++){
		sex = (uniq_title[i].charCodeAt(0)+uniq_title[i].charCodeAt(uniq_title[i].length-1))/8;
		var my_chance=new Chance(sex);
		var mycolor = my_chance.color({format: 'hex'});
		var $selector = $('<div class="item add-intern" id="'+uniq_title[i]+'" data-value="'+uniq_title[i]+'"><div class="ui green empty circular label" style="'+mycolor+'"></div>'+uniq_title[i]+'</div>');
		$("#intern-selector").append($selector);
	}

	//配列整形→色挿入
	for(var i=0;i<shoya.length;i++){
		sex = (shoya[i].title.charCodeAt(0)+shoya[i].title.charCodeAt(shoya[i].title.length-1))/8;
		var my_chance=new Chance(sex);
		shoya[i].color = my_chance.color({format: 'hex'});
		start = new Date(Date.parse(shoya[i].start));
		end = new Date(Date.parse(shoya[i].end));
		shoya[i].tooltip = '<div id="tooltip">'+shoya[i].title+'<br/>'+toDoubleDigits(start.getHours())+':'+toDoubleDigits(start.getMinutes())+'-'+toDoubleDigits(end.getHours())+':'+toDoubleDigits(end.getMinutes());
	}


	$('#calendar').fullCalendar({
		header: {
			left: 'prev,next today',
			center: 'title',
			right: 'agendaWeek,agendaDay,month'
		},
    height: 700,
		defaultView: 'agendaWeek',
		lang: "ja",
		slotEventOverlap: false,
		displayEventTime: false,
		allDaySlot: false,
		minTime: '07:00:00',
		maxTime: '21:00:00',
		defaultDate: nowdate.getFullYear()+'-'+(nowdate.getMonth() + 1)+'-'+nowdate.getDate(),
		navLinks: false, // can click day/week names to navigate views
		editable: false,
		eventLimit: true, // allow "more" link when too many events
		views: {
	        agenda: {
	            eventLimit: 2 // adjust to 6 only for agendaWeek/agendaDay
	        },
	        week: {
	            // options apply to basicWeek and agendaWeek views
	            eventLimit: 2
	        },
	    },
	    eventMouseover: function(calEvent, jsEvent) {
	        $('body').prepend(calEvent.tooltip);

	        xOffset = 10 + $('#tooltip').height();
	        yOffset = -10;

	        $('#tooltip')
	        .css('top', (jsEvent.clientY - xOffset) + 'px')
	        .css('left', (jsEvent.clientX + yOffset) + 'px')
	        .fadeIn();
	    },

	    eventMouseout: function(calEvent, jsEvent) {
	        $('#tooltip').remove();
	    },
			eventRender: function(events, element) {
			    $(element.context)  //imgプロパティが存在するイベントだけtitleを画像に差し替え
					.html(events.open_div+events.border+events.username+events.schedule+events.tasks+events.close_div);
    	},
			events:shoya
	});
});

$(function() {
// チェックボックスをチェックしたら発動
	$('.add-intern').on('click', function() {
		var new_event = [];
		$(this).addClass("selected-intern");
		for(var i=0;i<uniq_title.length;i++){
			if($('#'+uniq_title[i]).hasClass('selected-intern')){
				for(var j=0;j<shoya.length;j++){
					if(uniq_title[i]===shoya[j].title){
						new_event.push(shoya[j]);
					}
				}
			}
		}
		$('#calendar').fullCalendar( 'removeEvents' );
		$('#calendar').fullCalendar( 'renderEvents', new_event,'stick' );
  });
});

</script>
  <h3>スケジュール
		<% if current_user.employment_status == true %>
			<%= link_to new_schedule_path, class: "ui right floated button interne-icon-btn" do%>
				<i class="plus icon"></i>
			<% end %>
		<% end %>
		<div class="ui multiple dropdown">
		  <input type="hidden" name="filters">
		  <i class="filter icon"></i>
		  <span class="text">インターン生を選択</span>
		  <div class="menu">
		    <div class="ui icon search input">
		      <i class="search icon"></i>
		      <input type="text" placeholder="インターン生を検索...">
		    </div>
		    <div class="scrolling menu" id="intern-selector">
		    </div>
		  </div>
		</div>
	</h3>
	<div class="ui grid">
    <div class="row">
      <div class="sixteen wide column">
        <div id='calendar'></div>
      </div>
    </div>
  </div>

app/views/dashboard/_tasks.html.erb
<script type="text/javascript">
		$(document).ready(function(){
			$('.ui.dropdown').dropdown();
		});
</script>
<h3>
	タスク
	<%= link_to new_task_path, class: "ui right floated button interne-icon-btn" do%>
		<i class="plus icon"></i>
	<% end %>
</h3>
<% iter1 = 0 %>
<% if @schedules != [] %>
  <div class="ui relaxed divided list task-status" id="tasks-for-all">
    <% @schedules.each do |schedule| %>
      <% schedule.tasks.each do |task| %>
          <div class="tasks<%= iter1 %>" style="cursor : pointer;">
            <div class="item">
							<% color = user_color_list(user_id:task.users.first.id,company_id:current_company.id) %>
              <div class="left-gradient-border" style="background: linear-gradient(-45deg,<%= color.grad_1 %>,<%= color.grad_2 %>);"></div>
						  <div class="circle-image-border" style="width: 40px; height: 40px; left: 1rem; margin-top: -20px;  background: linear-gradient(-45deg,<%= color.grad_1 %>,<%= color.grad_2 %>);">
								<span><%= image_tag task.users.first.profile_photo_url, class:"company-icon-img"%></span>
							</div>
	          	<div class="content">
		          <div class="title">
	              	<%= task.title %>
									<% task.labels.each do |label| %>
	                  <span class="labelname" style="background-color:<%=label.color%>;">
	                    <%= label.name %>
	                  </span>
	                <% end %>
									<% task.users.each do |user| %>
										<span class="username">
											<%= user.name %>,
										</span>
									<% end %>
	              </div>
	              <div class="description">
	                  <%=task.detail.slice(0, 40)%><%= '...' if task.detail.length > 40%>
	                <span>
	                  <%= schedule.work_started_at.strftime("%m月%d日") %>
	                </span>
	              </div>
	            </div>
						</div>
          </div>

          <!-- modal -->
					<div class="ui tiny modal taskons<%= iter1 %>">
						<i class="close icon"></i>
						<div class="header">
							<% task.task_users.each do |task_user| %>
							<%= image_tag task_user.user.profile_photo_url ,class:"ui avatar image",style:"height:25px;width:25px;"%>
							<%= task_user.user.name %>
							<%= schedule.work_started_at %>
						</div>
						<div class="content">
							<div class="description">
								<div class="ui header"><%= task.title %></div>
								<%= task.detail %>
								<br><br>
								<% task.labels.each do |label| %>
								<span class="labelname" style="background-color:<%=label.color%>;">
									<%= label.name %>
								</span>
								<% end %><br><br>
								作成日時：<%= task.created_at.strftime("%m月%d日 %-H時%M分") %><br>
								最終更新日時：<%= task.updated_at.strftime("%m月%d日 %-H時%M分") %><br>
							</div>
						</div>
						<div class="actions">
							<%= link_to edit_task_path(task) ,class:"ui button" do%>
							編集
							<%end%>
							<div class="ui deny button">
								戻る
							</div>
						</div>
					</div>
          <script type="text/javascript">
						$(function(){
							$('.tasks<%= iter1 %>').on('click',function(){
							 $('.ui.modal.taskons<%= iter1 %>').modal('show');
							});
						});
				  </script>
				  <% iter1 = iter1 + 1 %>
        <% end %>
      <% end %>
		<% end %>
	  <% @tasks_not_desided_day.each do |task| %>
		    <div class="tasks<%= iter1 %>" style="cursor : pointer;">
          <div class="item" style="border-left: 4px solid <%= task.labels == [] ? '#ffffff' : task.labels.last.color%>;">
						<% if task.users != [] %>
							<% color = user_color_list(user_id:task.users.first.id,company_id:current_company.id) %>
							<div class="left-gradient-border" style="background: linear-gradient(-45deg,<%= color.grad_1 %>,<%= color.grad_2 %>);"></div>
							<div class="circle-image-border" style="width: 40px; height: 40px; left: 1rem; margin-top: -20px;  background: linear-gradient(-45deg,<%= color.grad_1 %>,<%= color.grad_2 %>);">
								<span><%= image_tag task.users.first.profile_photo_url, class:"company-icon-img"%></span>
							</div>
						<% end %>
						<div class="content">
	            <div class="title">
              	<%= task.title %>
								<% task.labels.each do |label| %>
                  <span class="labelname" style="background-color:<%=label.color%>;">
                    <%= label.name %>
                  </span>
                <% end %>
								<% task.users.each do |user| %>
									<span class="username">
										<%= user.name %>,
									</span>
								<% end %>
              </div>
              <div class="description">
                <%=task.detail.slice(0, 40)%><%= '...' if task.detail.length > 40%>
              </div>
            </div>
					</div>
        </div>

        <!-- modal -->
        <div class="ui tiny modal taskons<%= iter1 %>">
			  <i class="close icon"></i>
			  <div class="header">
			  	<% task.task_users.each do |task_user| %>
				      <%= image_tag task_user.user.profile_photo_url ,class:"ui avatar image",style:"height:25px;width:25px;"%>
				      <%= task_user.user.name %>
				<% end %>
			  </div>
			  <div class="content">
			    <div class="description">
			      <div class="ui header"><%= task.title %></div>
			      <%= task.detail %>
			      <br><br>
			      <% task.labels.each do |label| %>
              <span class="labelname" style="background-color:<%=label.color%>;">
                <%= label.name %>
              </span>
            <% end %><br><br>
            作成日時：<%= task.created_at.strftime("%m月%d日 %-H時%M分") %><br>
            最終更新日時：<%= task.updated_at.strftime("%m月%d日 %-H時%M分") %><br>
			    </div>
			  </div>
			  <div class="actions">
			    <%= link_to edit_task_path(task) ,class:"ui button" do%>
			      編集
			      <%end%>
			    <div class="ui deny button">
			      戻る
			    </div>
			  </div>
		    </div>

          <script type="text/javascript">
			$(function(){
				$('.tasks<%= iter1 %>').on('click',function(){
				 $('.ui.modal.taskons<%= iter1 %>').modal('show');
				});
			});
		  </script>
		  <% iter1 = iter1 + 1 %>
    <% end %>
  </div>
<% else %>
  <div class="ui grid padded stackable middle aligned" id="schedule-status-for-intern">
    <div class="sixteen wide column center aligned">
    <%= "タスクが登録されていません。" %>
    </div>
</div>
<% end %>

app/views/dashboard/_users.html.erb
<h3>インターンシップ生</h3>
<div class="ui cards stackable">
  <% @users.each do |user| %>
  <div class="card">
    <div class="content">
      <div class="ui dropdown right floated">
      	<i class="options icon"></i>
      	<div class="menu">
          <% if user.id == current_user.id %>
    		    <%= link_to user ,class: "item" do%>詳細<% end%>
    		    <%= link_to edit_task_path(user) ,class: "item" do%>編集<% end%>
    		    <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } ,class: "item" do%>削除<%end%>
		      <% else %>
    		    <%= link_to user ,class: "item" do%>詳細<% end%>
		      <% end %>
      	</div>
      </div>
      <%= image_tag user.profile_photo_url, class: "ui left floated avatar image"%>
      <div class="header">
        <%= user.name %>
      </div>
      <div class="meta">
        <%= user.university %> <%= user.department %> <%= user.grade %>年
      </div>
      <div class="description">
        「<% if user.goals != [] %>
	        <%= user.goals.last.title %>
	      <% else %>
	        目標が登録されていません:(
	      <% end %>」
      </div>
    </div>
    <div class="extra content">
      <span class="right floated">
        　<% if user.schedules != [] %>
	        <%= user.schedules.last.work_started_at.strftime('%m/%d(%a) %-H:%M') %>
	      <% else %>
	        登録されていません
	      <% end %>
      </span>
      <span>
        <i class="calendar icon"></i>
        次回出勤
      </span>
    </div>
  </div>
  <% end %>
</div>