config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :labels
  # authenticated :user do
    root to: "dashboard#index"
  # end
  get 'notices/update_notice', to: 'notices#update_notice'
  get 'mypage', to: 'users#mypage', as: 'mypage'
  get 'users/update_user_after_login', to: 'users#update_user_after_login', as: 'update_user_after_login'
  get 'stamps/remove_stamp', to: 'stamps#remove_stamp', as: 'remove_stamp'
  get 'stamps/press_stamp', to: 'stamps#press_stamp', as: 'press_stamp'
  get 'dashboard/index', to: 'dashboard#set_current_company', as: 'set_current_company'
  get 'companies/associate_intern', to: 'companies#associate_intern', as: 'associate_intern'
  get 'attendances/start_work', to: 'attendances#start_work', as: 'start_work'
  get 'attendances/stop_work', to: 'attendances#stop_work', as: 'stop_work'
  get 'attendances/start_break', to: 'attendances#start_break', as: 'start_break'
  get 'attendances/stop_break', to: 'attendances#stop_break', as: 'stop_break'
  resources :stamps
  resources :companies
  resources :todos
  resources :notices
  resources :attendances
  resources :goals
  resources :reports
  resources :schedules
  resources :tasks
  devise_scope :user do
    patch "users/confirmation", to: "users/confirmations#confirm"
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: "users/confirmations"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :users, only: [] do
    get "/schedules", to: "schedules#selected_user_schedules", as:"selected_user_schedules"
  end
end

app/models/task.rb
class Task < ApplicationRecord
  # belongs_to :user, optional: true
  belongs_to :company
  has_many :task_schedules
  has_many :schedules, through: :task_schedules
  has_many :task_notices
  has_many :notices, through: :task_notices
  has_many :task_labels
  has_many :labels, through: :task_labels
  has_many :task_users
  has_many :users, through: :task_users

  def self.associate_task(params:, task:)
    user_id = params[:task][:task_users][:user_id]
    unless user_id.blank?
      user = User.find(user_id)
      user.tasks << task
    end
    schedule_id = params[:task][:task_schedules][:schedule_id]
    unless schedule_id.blank?
      schedule = Schedule.find(schedule_id)
      schedule.tasks << task
    end
    label_id = params[:task][:task_labels][:label_id]
    unless label_id.blank?
      label = Label.find(label_id)
      label.tasks << task
    end
  end

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_company.tasks.all.page(params[:page]).per(20).search(params[:search]).reverse_order if params[:sort] == nil && params[:uesr_id] == nil
    @tasks = current_company.tasks.order(params[:sort]).page(params[:page]).per(20) if params[:sort] != nil
    @tasks = current_company.tasks.where(user_id: params[:user_id]).reverse_order.page(params[:page]).per(20) if params[:user_id] != nil
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    Task.associate_task(params:params, task: @task)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end

    #お知らせ生成
    if @task.task_users != []
      if params[:user_id] != [] && params[:schedule_id] != []
        name = current_user.name
        title = @task.title
        day = @task.task_schedules.first.schedule.work_started_at.strftime("%m月%d日") unless @task.task_schedules == []
        users_id_arr = []
        users_id_arr.append(@task.task_users.first.user.id)
        generate_notice(users_id:users_id_arr, companies_id:companies_id_arr, body:"#{name}さんが#{day}のあなたの タスク「#{title}」を追加しました", associate_type:"task", associate_id: @task.id)
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    Task.associate_task(params:params, task: @task)
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:user_id, :company_id, :schedule_id, :title, :detail)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true, class: "ui form") do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :company_id, value: current_company.id %>
  </div>

  <div class="field">
    <%= form.fields_for :task_users do |task_user| %>
      <%= task_user.label 'インターン生を選択' %>
      <% user_options = current_company.users.order(:id).map { |user| [user.name, user.id, data: { schedule_path: user_selected_user_schedules_path(user.id) }] } %>
      <%= task_user.select :user_id, user_options, { include_blank: true }, class: 'select-user'%>
    <% end %>
  </div>

  <div class="field">
    <%= form.fields_for :task_schedules do |task_schedule| %>
      <%= task_schedule.label '日程を選択' %>
        <% if schedules = @task.users.try(:schedules) || [] %>
        <% schedule_options = schedules.map { |schedule| [schedule.work_started_at, schedule.id] } %>
        <%= task_schedule.select :schedule_id, schedule_options, { include_blank: true }, class: 'select-schedule' %>
      <% end %>
    <% end %>
  </div>
  
  <div class="field">
    <%= form.fields_for :task_labels do |task_label| %>
      <%= task_label.label 'ラベルを選択' %>
      <%= task_label.collection_select :label_id, current_company.labels, :id, :name ,{ include_blank: true }%>
    <% end %>
  </div>

  <div class="field">
    <%= form.label 'タスクのタイトル' %>
    <%= form.text_field :title, id: :task_title %>
  </div>

  <div class="field">
    <%= form.label 'タスクの詳細' %>
    <%= form.text_area :detail, id: :task_detail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to '詳細', @task %> |
<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<script type="text/javascript">
		$(document).ready(function(){
			$('.ui.dropdown').dropdown();
		});
</script>

<p id="notice"><%= notice %></p>

<%= form_tag tasks_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "検索", :name => nil %>
<% end %>

<div class="ui grid">
  <div class="four column row">
    <div class="left floated column">
    	<%= link_to new_task_path, class: "ui labeled icon button" do%>
    	<i class="plus icon"></i>タスクを追加
    	<% end %>
    </div>
		<div class="left floated column">
    	<%= link_to labels_path, class: "ui button" do%>
			ラベル管理
    	<% end %>
    </div>
    <div class="right floated column right aligned">
		<div class="ui dropdown right aligned">
		  <div class="text" style="color:#2185D0;text-decoration: underline;">日付別</div>
		  <i class="dropdown icon blue" style="margin:0px;"></i>
		  <div class="menu">
		    <%= link_to("投稿日(昇順)", { sort:"created_at desc" }, class: "item") %>
		    <%= link_to("投稿日(降順)", { sort:"created_at" }, class: "item") %>
		  </div>
		</div>
		/
		<div class="ui dropdown right floated">
		  <div class="text" style="color:#2185D0;text-decoration: underline;">人物別</div>
		  <i class="dropdown icon blue" style="margin:0px;"></i>
		  <div class="menu">
		    <% current_company.users.each do |user| %>
		     <%= link_to(user.name, { user_id: user.id }, class: "item") %>
		    <% end %>
		  </div>
		</div>
    </div>
</div>
</div>



<div class="ui relaxed divided list">
<% @tasks.each do |task| %>
  <div class="item">
    <div class="right floated content">
      <%= link_to edit_task_path(task), class:"ui button" do%>
      編集
      <%end%>
      <%= link_to task, method: :delete, data: { confirm: '本当に削除しますか？' }, class:"ui button" do%>
      削除
      <%end%>
    </div>
    <img class="ui avatar image middle aligned icon" src="https://semantic-ui.com/images/avatar2/small/rachel.png">
    <div class="content">
      <%= link_to task ,class: "header" do%>
      	<%= task.title %>
      <%end%>
      <div class="description">
      <%= task.detail %>
      <% task.task_schedules.each do |task_schedule| %>
        <%= task_schedule.schedule.work_started_at.strftime('%m/%d(%a)') %><br>
      <% end %>
			<% task.task_schedules.each do |task_schedule| %>
        <%= task_schedule.schedule.work_started_at.strftime('%m/%d(%a)') %><br>
      <% end %>
			<% task.task_labels.each do |task_label| %>
        <div style="background-color:<%= task_label.label.color %>;"><%= task_label.label.name%></div>
      <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>

  <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h1>タスクを追加</h1>

<%= render 'form', task: @task %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h3>担当：
    <% @task.task_users.each do |task_user| %>
      <%= image_tag task_user.user.profile_photo_url %>
      <%= task_user.user.name %>
    <% end %>
  </h3>
  <h3>タイトル：<%= @task.title %></h3>
  <h3>内容：<%= simple_format(@task.detail) %></h3>
  <h3>予定：
    <% @task.task_schedules.each do |task_schedule| %>
      <%= task_schedule.schedule.work_started_at %>
    <% end %>
  </h3>
  <h3>ラベル：
    <% @task.task_labels.each do |task_label| %>
      <%= task_label.label.name %>
    <% end %>
  </h3>
  <h3>作成日時：<%= @task.created_at.strftime("%m月%d日 %-H時%M分") %></h3>
  <h3>最終更新日時：<%= @task.updated_at.strftime("%m月%d日 %-H時%M分") %></h3>
</div>

<div>
  <%= link_to '編集', edit_task_path(@task)%>
  <%= link_to '戻る', tasks_path%>
</div>