config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :labels
  # authenticated :user do
    root to: "dashboard#index"
  # end
  get 'notices/update_notice', to: 'notices#update_notice'
  get 'mypage', to: 'users#mypage', as: 'mypage'
  get 'users/update_user_after_login', to: 'users#update_user_after_login', as: 'update_user_after_login'
  get 'stamps/remove_stamp', to: 'stamps#remove_stamp', as: 'remove_stamp'
  get 'stamps/press_stamp', to: 'stamps#press_stamp', as: 'press_stamp'
  get 'dashboard/index', to: 'dashboard#set_current_company', as: 'set_current_company'
  get 'companies/associate_intern', to: 'companies#associate_intern', as: 'associate_intern'
  get 'attendances/start_work', to: 'attendances#start_work', as: 'start_work'
  get 'attendances/stop_work', to: 'attendances#stop_work', as: 'stop_work'
  get 'attendances/start_break', to: 'attendances#start_break', as: 'start_break'
  get 'attendances/stop_break', to: 'attendances#stop_break', as: 'stop_break'
  resources :stamps
  resources :companies
  resources :todos
  resources :notices
  resources :attendances
  resources :goals
  resources :reports
  resources :schedules
  resources :tasks
  devise_scope :user do
    patch "users/confirmation", to: "users/confirmations#confirm"
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: "users/confirmations"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :users, only: [] do
    get "/schedules", to: "schedules#selected_user_schedules", as:"selected_user_schedules"
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :tasks
  has_many :labels
  has_many :schedules
  has_many :goals
  has_many :reports
  has_many :attendances
  has_many :notice_companies
  has_many :notices, through: :notice_companies
  has_many :todo_companies
  has_many :todos, through: :todo_companies
  has_many :company_users
  has_many :users, through: :company_users

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    users = current_company.users.where(employment_status:1)
    @users = users.page(params[:page]).per(10)
    @searched_users = User.all.page(params[:page]).per(10).search(params[:search])
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def associate_intern
    company_id = current_user.company_users.first.company_id.to_i
    @company_user = CompanyUser.new(user_id:params[:user_id], company_id:company_id)
    respond_to do |format|
      if @company_user.save
        format.html { redirect_back(fallback_location: root_path, notice: params[:user_name]+'さんを招待しました')}
        format.json { render :show, status: :created, location: @company_user }
      else
        format.html { render :new }
        format.json { render json: @company_user.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/_users.html.erb
<div class="ui cards stackable">
  <% users.each do |user| %>
  <div class="card">
    <div class="content">
      <div class="ui dropdown right floated">
      	<i class="options icon"></i>
      	<div class="menu">
      	    <% if user.id == current_user.id %>
		    <%= link_to user ,class: "item" do%>詳細<% end%>
		    <%= link_to edit_task_path(user) ,class: "item" do%>編集<% end%>
		    <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } ,class: "item" do%>削除<%end%>
		    <% else %>
		    <%= link_to user ,class: "item" do%>詳細<% end%>
		    <% end %>
      	</div>
      </div>
      <%= image_tag user.profile_photo_url, class: "ui left floated mini image"%>
      <div class="header">
        <%= user.name %>
      </div>
      <div class="meta">
        <%= user.university %> <%= user.department %> <%= user.grade %>年
      </div>
      <div class="description">
        「<% if user.goals != [] %>
	        <%= user.goals.last.title %>
	      <% else %>
	        目標が登録されていません:(
	      <% end %>」
      </div>
    </div>
    <div class="extra content">
      <span class="right floated">
        　<% if user.schedules != [] %>
	        <%= user.schedules.last.work_started_at.strftime('%m/%d(%a) %-H:%M') %>
	      <% else %>
	        登録されていません
	      <% end %>
      </span>
      <span>
        <i class="calendar icon"></i>
        次回出勤
      </span>
    </div>
  </div>
  <% end %>
</div>
<div>
  <%= paginate @users %>
</div>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to '詳細', @company %> |
<%= link_to '戻る', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to '詳細', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to '戻る', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui center aligned raised segment" style="z-index:-5;">
  <%= image_tag @company.home_photo_url %>
  <%= image_tag  @company.icon_photo_url %>
  <h1><%= @company.name %></h1>
  <p><%= @company.hp_addr %><p>
</div>
<div class="ui raised segment" style="z-index:-5;">
  <%= render "users", users: @users%>
</div>

<div class="ui raised segment">
  <h3>新しいインターン生を招待</h3>
  ユーザ検索
  <%= form_tag request.url, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "検索", :name => nil %>
  <% end %>
  <% if params[:search] != nil %>
    <% @searched_users.each do |searched_user| %>
      <%= link_to searched_user do%>
        <div class="wrap-for-dev">
          <div>
            <%= image_tag searched_user.profile_photo_url%>
          </div>
          <div>
            <div>
              <h3><%= searched_user.name %></h3>
            </div>
            <div>
              <%= searched_user.university %> <%= searched_user.department %> <%= searched_user.grade %>年
            </div>
          </div>
          <div>
            <%= link_to '詳細', searched_user ,class: "btn btn-default"%>
            <%= link_to 'チームに招待', associate_intern_url(:user_id => searched_user.id, :user_name => searched_user.name, :company_id => current_user.company_users.first.company.id)%>
          </div>
        </div>
      <% end %>
    <% end %>
    <%= paginate @searched_users %>
  <% end %>
</div>


<%= link_to '編集', edit_company_path(@company) %>