config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :labels
  # authenticated :user do
    root to: "dashboard#index"
  # end
  get 'notices/update_notice', to: 'notices#update_notice'
  get 'mypage', to: 'users#mypage', as: 'mypage'
  get 'users/update_user_after_login', to: 'users#update_user_after_login', as: 'update_user_after_login'
  get 'stamps/remove_stamp', to: 'stamps#remove_stamp', as: 'remove_stamp'
  get 'stamps/press_stamp', to: 'stamps#press_stamp', as: 'press_stamp'
  get 'dashboard/index', to: 'dashboard#set_current_company', as: 'set_current_company'
  get 'companies/associate_intern', to: 'companies#associate_intern', as: 'associate_intern'
  get 'attendances/start_work', to: 'attendances#start_work', as: 'start_work'
  get 'attendances/stop_work', to: 'attendances#stop_work', as: 'stop_work'
  get 'attendances/start_break', to: 'attendances#start_break', as: 'start_break'
  get 'attendances/stop_break', to: 'attendances#stop_break', as: 'stop_break'
  resources :stamps
  resources :companies
  resources :todos
  resources :notices
  resources :attendances
  resources :goals
  resources :reports
  resources :schedules
  resources :tasks
  devise_scope :user do
    patch "users/confirmation", to: "users/confirmations#confirm"
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: "users/confirmations"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :users, only: [] do
    get "/schedules", to: "schedules#selected_user_schedules", as:"selected_user_schedules"
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :schedule
  belongs_to :company
  has_many :report_notices
  has_many :notices, through: :report_notices
  has_many :report_todos
  has_many :todos, through: :report_todos
  has_many :report_stamps
  has_many :stamps, through: :report_stamps
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  # GET /reports
  # GET /reports.json
  def index
    @reports = current_company.reports.reverse_order.page(params[:page]).per(10) if params[:sort] == nil && params[:uesr_id] == nil
    @reports = current_company.reports.order(params[:sort]).page(params[:page]).per(10) if params[:sort] != nil
    @reports = current_company.reports.where(user_id: params[:user_id]).reverse_order.page(params[:page]).per(10) if params[:user_id] != nil
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @report.update(work_started_at: @report.schedule.work_started_at)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end

    #Todo生成
    name = current_user.name
    title = params[:report][:title]
    day = Schedule.find(params[:report][:schedule_id]).work_started_at.strftime("%m月%d日")
    generate_todo(users_id:staffs_id_arr, companies_id:companies_id_arr, body:"#{name}さんが#{day}出社分の日報「#{title}」を作成しました。確認してスタンプを押しましょう。", associate_type:"report", associate_id: @report.id)

    #update Todo
    update_todo(associate_type:"schedule", associate_id: @report.schedule.id)
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:user_id, :company_id, :title, :schedule_id, :body, schedules_attributes: [:schedule_id])
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true, class: "ui form") do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.hidden_field :company_id, value: current_company.id %>
  </div>

  <div class="field">
    <%= form.label "出勤日を選択" %>
    <% @current_user_schedules = current_company.schedules.where(user_id:current_user.id) %>
    <%= form.collection_select :schedule_id, @current_user_schedules, :id, :simple_work_started_at %>
  </div>

  <div class="field">
    <%= form.label "タイトルを入力" %>
    <%= form.text_field :title, id: :report_title %>
  </div>

  <div class="field">
    <%= form.label "詳細を入力" %>
    <%= form.text_area :body, id: :report_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>日報を編集</h1>

<%= render 'form', report: @report %>

<%= link_to '詳細', @report %> |
<%= link_to '戻る', reports_path %>

app/views/reports/index.html.erb
<script type="text/javascript">
		$(document).ready(function(){
			$('.ui.dropdown').dropdown();
		});
</script>


<p id="notice"><%= notice %></p>
<div class="ui grid">
  <div class="four column row">
    <div class="left floated column">
    	<%= link_to new_report_path, class: "ui labeled icon button" do%>
    	<i class="plus icon"></i>日報を追加
    	<% end %>
    </div>
    <div class="right floated column right aligned">
			<div class="ui dropdown right aligned">
			  <div class="text" style="color:#2185D0;text-decoration: underline;">日付別</div>
			  <i class="dropdown icon blue" style="margin:0px;"></i>
			  <div class="menu">
			    <%= link_to("投稿日(昇順)", { sort:"created_at desc" }, class: "item") %>
			    <%= link_to("投稿日(降順)", { sort:"created_at" }, class: "item") %>
			    <%= link_to("出勤日(昇順)", { sort:"schedule_id desc" }, class: "item") %>
			    <%= link_to("出勤日(降順)", { sort:"schedule_id" }, class: "item") %>
			  </div>
			</div>
			/
			<div class="ui dropdown right floated">
			  <div class="text" style="color:#2185D0;text-decoration: underline;">人物別</div>
			  <i class="dropdown icon blue" style="margin:0px;"></i>
			  <div class="menu">
			    <% current_company.users.each do |user| %>
			     <%= link_to(user.name, { user_id: user.id }, class: "item") %>
			    <% end %>
			  </div>
			</div>
	  </div>
	</div>
</div>

<div class="ui four cards stackable" style="margin-left:-1em; margin-right:-1em; margin-top:0px; margin-bottom:0px;">
  <% @reports.each do |report| %>
  <div class="card">
    <div class="content" style="background-image: url('../assets/mima-opa.png');background-position: right bottom; background-repeat: no-repeat;">
      <% if report.user_id == current_user.id %>
      <div class="ui dropdown right floated">
      	<i class="options icon"></i>
      	<div class="menu">
      		    <%= link_to report ,class: "item" do%>詳細<% end%>
      		    <%= link_to edit_report_path(report) ,class: "item" do%>編集<% end%>
      		    <%= link_to report, method: :delete, data: { confirm: '本当に削除しますか？' } ,class: "item" do%>削除<%end%>
      	</div>
      </div>
      <% end %>
      <div class="meta">
        <%= report.schedule.work_started_at.strftime('%m/%d') %>
      </div>
      <div class="header">
				<%= report.title %>
      </div>
      <div class="description">
        <div style="font-size:10px;"><%= report.body %></div>
      </div>
    </div>
    <div class="extra content" style="padding: 1.5em 1em;">
			<% color = user_color_list(user_id:report.user.id,company_id:current_company.id) %>
			<div class="circle-image-border" style="width: 40px; height: 40px; left: 1rem; margin-top: -20px; linear-gradient(-45deg,<%= color.grad_1 %>,<%= color.grad_2 %>); %>
			;">
				<span><%= image_tag report.user.profile_photo_url, class:"company-icon-img"%></span>
			</div>
			<div style="padding-left:3.5rem;"><%= report.user.name %></div>
		</div>
    <div class="extra content">
	    <div class="item">
	      <% report.report_stamps.each_with_index do |report_stamp,i| %>
	      	<%if i==0 && report.report_stamps.length==1 %>
	      	  <%= image_tag report_stamp.stamp.url ,class:"ui mini image left floated",style:"width:17px;height:17px;margin-bottom:0px;margin-right:0.5em;"%>
	      	  <div class="left floated" style="font-size:9px;"><%= report_stamp.user.name %></div>
	      	<%elsif i==0%>
	      	  <%= image_tag report_stamp.stamp.url ,class:"ui mini image left floated",style:"width:17px;height:17px;margin-bottom:0px;margin-right:0.5em;"%>
	      	  <div class="left floated" style="font-size:9px;"><%= report_stamp.user.name %>など<%= report.report_stamps.length %>人</div>
	      	<%end%>
		　   <% end %>
	    <div class="ui dropdown right floated" style="display:block;display: flow-root;">
        <div style="font-size:9px">スタンプ送信</div>
          <div class="menu">
            <% stamps.each do |stamp| %>
              <div class="item">
              <%= link_to press_stamp_path(stamp_id:stamp.id,associate_type:"report",associate_id:report.id) do%>
                  <%= image_tag stamp.url %>
              <% end %>
              </div>
            <% end %>
          </div>
        </div>
	    </div>
    </div>
  </div>
  <% end %>
</div>

<%= paginate @reports %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to '戻る', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui grid">
  <div class="three column row">
    <div class="wide column">
      <div class="ui tiny horizontal list" style="padding-top:0px;">
        <div class="item">
          <%= image_tag @report.user.profile_photo_url ,class:"ui avatar image"%>
          <div class="content">
            <div class="header"><%= @report.user.name %></div>
          </div>
          </div>
       </div>
    </div>
    <div class="center aligned wide column"><h1>日報</h1></div>
    <div class="right aligned wide column">
      <a class="header"><%= @report.schedule.work_started_at.strftime("%m月%d日") %></a>
    </div>
  </div>
</div>


<table class="ui celled striped table">
  <thead>
    <tr><th colspan="2" class="center aligned">
      <h3>「<%= @report.title %>」</h3>
    </th>
  </tr></thead>
  <tbody>
    <tr>
      <td class="collapsing">
        <i class="folder icon"></i> 本文 
      </td>
      <td><%= simple_format(@report.body) %></td>
    </tr>
    <tr>
      <td colspan="2">
        <div class="ui grid">
          <div class="two column row">
            <div class="wide column middle aligned">
                <% @report.report_stamps.each_with_index do |report_stamp,i| %>
                  <%if i==0 && @report.report_stamps.length==1 %>
                    <%= image_tag report_stamp.stamp.url ,class:"ui mini image left floated",style:"width:25px;height:25px;margin-bottom:0px;margin-right:0.5em;"%>
                    <div class="left floated" style="font-size:15px;margin-top:2px;"><%= report_stamp.user.name %></div>
                  <%elsif i==0%>
                    <%= image_tag report_stamp.stamp.url ,class:"ui mini image left floated",style:"width:25px;height:25px;margin-bottom:0px;margin-right:0.5em;"%>
                    <div class="left floated" style="font-size:15px;"><%= report_stamp.user.name %>など...<%= @report.report_stamps.length %>人</div>
                  <%end%>
               <% end %>
            </div>
            <div class="right aligned wide column">
              <div class="ui dropdown left aligned">
                <button class="ui button">
                  スタンプを押す</button>
                <div class="menu">
                  <% stamps.each do |stamp| %>
                    <%= link_to press_stamp_path(stamp_id:stamp.id,associate_type:"report",associate_id:@report.id) do%>
                      <div class="item">
                        <%= image_tag stamp.url %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <% if @report.user_id == current_user.id %>
                <%= link_to edit_report_path(@report),class:"ui button" do%>
                編集
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="content">


        </div>

      </td>
    </tr>
  </tbody>
</table>

<div class="ui grid">
  <div class="three column row">
    <div class="wide column"></div>
    <div class="wide column"></div>
    <div class="right aligned wide column">
      <a class="header">作成日時：<%= @report.created_at.strftime("%m月%d日 %-H時%M分") %><br>
      最終更新日時：<%= @report.updated_at.strftime("%m月%d日 %-H時%M分") %>
      </a>
    </div>
  </div>
</div>





<div>
  <%= link_to '＞＞日報一覧に戻る', reports_path%>
</div>